### ISSUE TITLE
Implement Flight Offers Price API

### ISSUE THREAD

**Issue by rukaiah-edhah** [rukaiah-edhah/Ijele#10]
As a user, I want to confirm the availability and final price of a flight, including any additional services, before booking.

- [x]  Set up the [Flight Offers Price API](https://developers.amadeus.com/get-started/create-a-flight-booking-engine-651) endpoint.
- [x] Implement logic to confirm flight availability and retrieve the final price.
- [x] Test the API endpoint

**Comment by Abutalibhasan** [comment]
@JenniferLarsen , I assigned my self to this issue, and started working on it, please let me know if you have any comments or concerns.

**Comment by Abutalibhasan** [comment]
I added the api function and the route for it and pushed it to my branch.

**Comment by rukaiah-edhah** [comment]
1. First, call the search endpoint to get flight offers:
`http://localhost:3000/api/flights/search?originLocationCode=PAR&destinationLocationCode=NYC&departureDate=2024-07-15&returnDate=2024-07-20&adults=2&max=5`
**Note: You may need to adjust the dates in the URL.**

2. After receiving the response from the search endpoint, copy the entire flight offer data from the response.

3. Next, use the copied flight offer data to test the pricing endpoint. Make a POST request to the following URL:
`http://localhost:3000/api/flights/price`
In the body of the POST request, replace **{{flightOfferData}}** with the copied flight offer data:
```
{
    "data": {
        "type": "flight-offers-pricing",
        "flightOffers": [
            {{flightOfferData}}
        ]
    }
}
```

This will allow you to test the pricing endpoint with the flight offers obtained from the search endpoint ;)

<img width="1160" alt="Screenshot 2024-07-14 at 9 58 56 AM" src="https://github.com/user-attachments/assets/b01e5a8e-0303-4564-80ec-94287e2c28ee">
