### ISSUE TITLE
Hotels/Airports/Accommodations Mockups

### ISSUE THREAD

**Issue by rukaiah-edhah** [rukaiah-edhah/Ijele#14]
As a user, I want to explore various hotels, airports, and accommodations to plan my travel effectively.

**Comment by CynCity098** [comment]
Finalized Ijele Page Mock-ups:
- Flight search results
- hotel search results
- checkout (flights/ hotels)

https://www.figma.com/design/AV3z93wbxSFWO7vkFwJ6tR/Ijele-MockUps?node-id=0-1&t=jeVZPRNRT2RSUiAy-1
