### ISSUE TITLE
Research and Experiment with Split Payment Functionality

### ISSUE THREAD

**Issue by rukaiah-edhah** [rukaiah-edhah/Ijele#2]
As a developer, I want to research and experiment with split payment functionality so that we can implement an effective solution in our project.

**Comment by rukaiah-edhah** [comment]
I've looked into the main steps to implement split payments. Based on my current search, here are the steps we need to take:

- [x] Set up the development environment
- [x] Develop API routes for user onboarding 
- [x] Integrate with external APIs (e.g., Amadeus API) to fetch listings and services (hotels, flights, etc.)
- [x] Use Stripe’s API to create account links and redirect users for onboarding.
- [x] Set up payment collection and implement logic to split payments between users 
- [ ] Use Stripe’s Transfer API to manage payouts (if needed)

**Comment by rukaiah-edhah** [comment]
For now, @JenniferLarsen and I have set up the environment and configured the Stripe SDK; our next steps include developing backend API routes for onboarding but that should be done after @Abutalibhasan sets up Vercel Postgres and implements the database schema for users and service providers.

**Comment by rukaiah-edhah** [comment]
We are done with the second task as well and will be focusing on fetching listings and services so that we can get back and work on the split feature.

**Comment by rukaiah-edhah** [comment]
For now, I will keep this issue open to track the tasks and prioritize what needs to be done before fully implementing the split payment functionality.

**Comment by JenniferLarsen** [comment]
We should now be able to begin work on the remaining portions of this issue.
