### ISSUE TITLE
Implement Flight APIs in Frontend

### ISSUE THREAD

**Issue by rukaiah-edhah** [rukaiah-edhah/Ijele#27]
As a user, I want to see flight offers, prices, and booking options integrated into the flight booking page, so that I can search for, select, and book flights :)

**Comment by JenniferLarsen** [comment]
Working on flight booking this week, flight search and pricing are already completed.

**Comment by rukaiah-edhah** [comment]
Traveler Details (for testing):

First Name: Jorge
Last Name: Gonzales
Gender: Male
Email Address: jorge.gonzales833@telefonica.es
Device Type: Mobile
Country Calling Code: 34
Phone Number: 480080076
Date of Birth: 1982-01-16

**Document Details:**
Document Type: Passport
Birth Place: Madrid
Issuance Location: Madrid
Date of Issuance: 2015-04-14
Passport Number: 00000000
Passport Expiration Date: 2025-04-14
Issuance Country Code: ES
Nationality Code: ES

**Comment by JenniferLarsen** [comment]
Flight API's are completed. Closing issue.

**Comment by JenniferLarsen** [comment]
Flight API's are completed. Closing issue.
