### ISSUE TITLE
Style Hotel Booking Page to Match Mockups

### ISSUE THREAD

**Issue by rukaiah-edhah** [rukaiah-edhah/Ijele#29]
As a user, I want the hotel booking page to match the [design mockups](https://www.figma.com/design/AV3z93wbxSFWO7vkFwJ6tR/Ijele-MockUps?node-id=0-1&t=pTHDSBH4u1wsXwCw-0) so that I have a visually appealing and consistent experience when searching for and booking hotels.

**Comment by CynCity098** [comment]
I will continue working towards this this week
