### ISSUE TITLE
Frontend Integration for Split Payment Feature

### ISSUE THREAD

**Issue by rukaiah-edhah** [rukaiah-edhah/Ijele#52]
Integrate the split payment feature into the frontend, including updating the flight and hotel booking pages to support group payment splitting

**Comment by JenniferLarsen** [comment]
Cart page has been added and Hotels and Flights can now be added to the cart and the payments set up to split on the front end.  Need multiple payments/parties available on the payment page still.

**Comment by JenniferLarsen** [comment]
Front-end Split payments are now fully functional. Closing issue.
