### ISSUE TITLE
Implement Hotel Search API

### ISSUE THREAD

**Issue by rukaiah-edhah** [rukaiah-edhah/Ijele#7]
As a user, I want to search for hotels by location and dates so that I can find accommodations that meet my needs.

- [x] Set up the [Hotel Search API](https://developers.amadeus.com/blog/build-hotel-booking-engine-amadeus-api) endpoint
- [x] Implement logic to handle search parameters and return results.
- [x] Test the API endpoint

**Comment by Abutalibhasan** [comment]
I figured out how the hotel offers api works and tested it, I just need to fetch the data and create the route & the component for it.

**Comment by rukaiah-edhah** [comment]
Yesterday, @Abutalibhasan and I had a meeting to try and resolve these errors. We are experiencing both of these errors interchangeably, and I'll spend the next couple of days figuring it out.
<img width="1313" alt="Screenshot 2024-07-05 at 11 25 20 AM" src="https://github.com/rukaiah-edhah/Ijele/assets/134958226/135efea7-6acf-4b4c-b448-8b998e646080">
<img width="904" alt="Screenshot 2024-07-05 at 11 26 53 AM" src="https://github.com/rukaiah-edhah/Ijele/assets/134958226/e17ea98d-59e2-4fad-9a0e-50b5a6223130">

**Comment by rukaiah-edhah** [comment]
Yesterday, @Abutalibhasan and I had a meeting to try and resolve these errors. We are experiencing both of these errors interchangeably, and I'll spend the next couple of days figuring it out.
<img width="904" alt="Screenshot 2024-07-05 at 11 26 53 AM" src="https://github.com/rukaiah-edhah/Ijele/assets/134958226/e48ad1a7-911f-4e69-b6b6-3832608d4de3">
<img width="1306" alt="Screenshot 2024-07-05 at 11 32 46 AM" src="https://github.com/rukaiah-edhah/Ijele/assets/134958226/9dc2dbd4-e17f-4bfe-810d-cfad566ee4b1">

**Comment by rukaiah-edhah** [comment]
The issue we were experiencing was that we were using invalid or unavailable hotel IDs. However, when I tested it today with different ones, it was successful.
<img width="1298" alt="Screenshot 2024-07-06 at 12 19 24 PM" src="https://github.com/rukaiah-edhah/Ijele/assets/134958226/1474e449-e497-4c9f-8387-f1ea7e054a6a">

**Comment by rukaiah-edhah** [comment]
Done.
